Make coz use Python 2 explicitly
Currently, the script will fail with the following error when the system default python is Python 3:
```
  File "/usr/bin/coz", line 32
    print 'error: specify a command to profile after `---`\n'
                                                            ^
SyntaxError: Missing parentheses in call to 'print'
```